name: Package Extension

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g., v1.2.3)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set version from input or tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            RAW_VERSION=${{ github.event.inputs.release_tag }}
          else
            RAW_VERSION=${GITHUB_REF#refs/tags/}
          fi

          VERSION="${RAW_VERSION#v}"  # Strip leading 'v' if present
          echo "VERSION=${VERSION:-1.0.0}" >> $GITHUB_ENV

      - name: Validate manifest.json
        run: |
          cat manifest.json | jq .

      - name: Update manifest version
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"${VERSION}\"/" manifest.json
          sed -i "s/CFBundleShortVersionString.*/CFBundleShortVersionString<\/key><string>${VERSION}<\/string>/" safari/Info.plist
          sed -i "s/CFBundleVersion.*/CFBundleVersion<\/key><string>${VERSION}<\/string>/" safari/Info.plist

      - name: Create Safari Package
        run: |
          # Create Safari directory structure
          mkdir -p safari/src
          
          # Copy source files
          cp -r src/* safari/src/
          
          # Copy manifest
          cp manifest.json safari/
          
          # Update Safari-specific files
          sed -i 's/chrome\./safari\.extension\./g' safari/src/js/*.js
          sed -i 's/"manifest_version": 3/"manifest_version": 2/' safari/manifest.json
          sed -i 's/"action"/"browser_action"/' safari/manifest.json
          sed -i 's/"service_worker"/"background"/' safari/manifest.json

      - name: Package Chrome/Edge/Brave Extension
        run: |
          zip -r px2-connect-chrome.zip \
            manifest.json \
            src/js/background.js \
            src/html/options.html \
            src/js/options.js \
            src/html/popup.html \
            src/js/popup.js \
            src/html/welcome.html \
            src/js/welcome.js \
            src/css/styles.css \
            src/css/popup.css \
            src/css/options.css \
            src/settings.ts \
            src/shortcuts.ts \
            src/chrome.d.ts \
            src/images/PF8-removebg-preview.png \
            src/images/px2.PNG \
            .github/workflows/package.yml \
            package.json \
            tsconfig.json \
            README.md \
            LICENSE

      - name: Package Safari Extension
        run: |
          cd safari
          zip -r ../px2-connect-safari.zip \
            manifest.json \
            Info.plist \
            src/js/background.js \
            src/html/options.html \
            src/js/options.js \
            src/html/popup.html \
            src/js/popup.js \
            src/html/welcome.html \
            src/js/welcome.js \
            src/css/styles.css \
            src/css/popup.css \
            src/css/options.css \
            src/settings.ts \
            src/shortcuts.ts \
            src/chrome.d.ts \
            src/images/PF8-removebg-preview.png \
            src/images/px2.PNG

      - name: Create GitHub Release (for manual run)
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          name: Release ${{ github.event.inputs.release_tag }}
          files: |
            px2-connect-chrome.zip
            px2-connect-safari.zip

      - name: Upload Artifacts (for manual run)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: px2-connect
          path: |
            px2-connect-chrome.zip
            px2-connect-safari.zip

      - name: Upload Release Packages (for tag-triggered release)
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            px2-connect-chrome.zip
            px2-connect-safari.zip