name: Package Extension

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Package Extension
        run: |
          # Create a temporary directory for extension files
          mkdir temp_extension
          # Copy only the required files
          cp manifest.json background.js options.html options.js popup.html popup.js PF8.png temp_extension/
          # Create the zip file
          cd temp_extension
          zip -r ../px2-connect.zip *
          cd ..

      - name: Upload Extension Package
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: px2-connect.zip

      - name: Upload Artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: px2-connect
          path: px2-connect.zip