name: Package Extension

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Update manifest version
        if: github.event_name == 'release'
        run: |
          # Get version from release tag (remove 'v' prefix)
          VERSION=${GITHUB_REF#refs/tags/v}
          # Update version in manifest.json
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" manifest.json

      - name: Package Extension
        run: |
          # Create zip file exactly like our working local version
          zip -r px2-connect.zip manifest.json background.js options.html options.js popup.html popup.js PF8-removebg-preview.png

      - name: Upload Extension Package
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: px2-connect.zip

      - name: Upload Artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: px2-connect
          path: px2-connect.zip